---
 - name: install standart packages
   yum: name={{ item }} state=latest 
   with_items:
    - audispd-plugins
 - name: cp auditd.conf
   copy: src=auditd.conf dest=/etc/audit/auditd.conf 
 - name: cp syslog.conf
   copy: src=syslog.conf dest=/etc/audisp/plugins.d/syslog.conf 
 - name: cp audit.rules
   copy: src=audit.rules dest=/etc/audit/rules.d/audit.rules
 - name: restart auditd
   shell: service auditd restart
