---
 - name: cp rsyslog.repo
   copy: src=rsyslog.repo dest=/etc/yum.repos.d/rsyslog.repo 
 - name: cp homeWork.conf
   copy: src=homeWork.conf dest=/etc/rsyslog.d/homeWork.conf
 - name: install nginx
   yum: name={{ item }} state=latest 
   with_items:
    - rsyslog
 - name: Restart rsyslog
   service: name=rsyslog state=restarted
