---
# - name: generate selinux rule for auditd
#   shell: checkmodule -M -m -o /vagrant/provisioning/roles/rsyslog-client/files/rsyslog.mod  /vagrant/provisioning/roles/rsyslog-client/files/rsyslog.te && semodule_package -o /vagrant/provisioning/roles/rsyslog-client/files/rsyslog.pp -m /vagrant/provisioning/roles/rsyslog-client/files/rsyslog.mod && semodule -i /vagrant/provisioning/roles/rsyslog-client/files/rsyslog.pp
 - name: cp homeWork
   copy: src=homeWork.conf dest=/etc/rsyslog.d/homeWork.conf
 - name: cp rsyslog.repo
   copy: src=rsyslog.repo dest=/etc/yum.repos.d/rsyslog.repo 
 - name: upd rsyslog
   yum: name={{ item }} state=latest 
   with_items:
    - rsyslog
 - name: cp rsyslog.conf
   copy: src=rsyslog.conf dest=/etc/rsyslog.conf 
 - name: Restart rsyslog
   service: name=rsyslog state=restarted
